Open source the fkv config files
dotnet-campus/dotnetCampus.Configurations pull request #1
Opened 2019-11-25 11:02 UTC by walterlv

2019-11-25 11:11 UTC, lindexi requested changes

2019-11-25 11:11 UTC, lindexi commented on src/dotnetCampus.Configurations/dotnetCampus.Configurations.csproj
> +    <RepositoryUrl>https://github.com/walterlv/dotnetCampus.Configurations.git</RepositoryUrl>
这里路径需要修改

2019-11-25 11:11 UTC, lindexi commented on src/dotnetCampus.Configurations/dotnetCampus.Configurations.csproj
> +    <PackageReference Include="dotnetCampus.SourceYard" Version="0.1.16539-alpha" PrivateAssets="all" />
使用 17750 版，解决WPF的坑

2019-11-25 12:04 UTC, kkwpsv requested changes

2019-11-25 12:04 UTC, kkwpsv commented on src/dotnetCampus.Configurations/ClassNameUtils.cs
> +        internal static string GetClassNameWithoutSuffix<T>(this T @this)
行为与注释不符
基类名为B
派生类名为ABC
结果返回为A

2019-11-25 12:04 UTC, kkwpsv commented on src/dotnetCampus.Configurations/Configuration.cs
> +            => _section = string.IsNullOrEmpty(sectionName) ? "" : $"{sectionName}.";
""要不要和下面统一用String.Empty

2019-11-25 12:04 UTC, kkwpsv commented on src/dotnetCampus.Configurations/Configuration.cs
> +        /// 不允许 <paramref name="value"/> 为 null；如果需要存入空值，请使用 <see cref="string.Empty"/>。
要不要抛出异常？

2019-11-25 12:04 UTC, kkwpsv commented on src/dotnetCampus.Configurations/Configuration.cs
> +        protected Configuration(string? sectionName)
处理下sectionName防止含有".",否则下面ClearValues可能误伤

2019-11-25 12:04 UTC, kkwpsv commented on src/dotnetCampus.Configurations/Configuration.cs
> +            // value?.ToString() 则可以在字符串为 null/"" 时拿到 null。
字符串为“”，不应该拿到“”吗？

2019-11-25 12:04 UTC, kkwpsv commented on src/dotnetCampus.Configurations/ConfigurationString.cs
> +            return value == null || string.IsNullOrEmpty(value) ? (ConfigurationString?)null : new ConfigurationString(value);
value == null || string.IsNullOrEmpty(value)
后者包含前者

2019-11-25 12:04 UTC, kkwpsv commented on src/dotnetCampus.Configurations/ConfigurationString.cs
> +            return _value is null || string.IsNullOrEmpty(_value) ? string.Empty : _value;
_value is null || string.IsNullOrEmpty(_value)
后者包含前者
并且此句等效于
return _value ?? String.Empty;

2019-11-25 12:04 UTC, kkwpsv commented on src/dotnetCampus.Configurations/ConfigurationString.cs
> +            return configurationValue?.ToString() ?? string.Empty;
configurationValue?.ToString()永不为null 不需要 "?? string.Empty"

2019-11-25 12:04 UTC, kkwpsv commented on src/dotnetCampus.Configurations/ConfigurationString.cs
> +        /// 注意，空字符串和 null 会被视为相等，因为这两者在 <see cref="ConfigurationString"/> 中表示的是相同含义。
似乎并不会。。

2019-11-25 12:04 UTC, kkwpsv commented on src/dotnetCampus.Configurations/ConfigurationString.cs
> +        public override int GetHashCode() => string.IsNullOrEmpty(_value) ? 0 : StringComparer.Ordinal.GetHashCode(_value);
只在null时返回0就好，不需要管Empty

2019-11-25 12:04 UTC, kkwpsv commented on src/dotnetCampus.Configurations/Core/AsynchronousConfigurationRepo.cs
> +            if (string.IsNullOrEmpty(key))
只判断 == String.Empty 就好

2019-11-25 12:04 UTC, kkwpsv commented on src/dotnetCampus.Configurations/Core/AsynchronousConfigurationRepo.cs
> +        void IConfigurationRepo.ClearValues(Predicate<string> keyFilter)
Predicate<string> 用 Func<string,bool>是不是好点

2019-11-25 12:04 UTC, kkwpsv commented on src/dotnetCampus.Configurations/Core/ConcurrentAppConfigurator.cs
> +        private readonly Dictionary<Type, Configuration> _configurationDictionary
ConcurrentDictionary 咋样

2019-11-25 12:07 UTC, walterlv commented on src/dotnetCampus.Configurations/dotnetCampus.Configurations.csproj
> +    <PackageReference Include="dotnetCampus.SourceYard" Version="0.1.16539-alpha" PrivateAssets="all" />
你需要修复两个在这个版本的 issue。

2019-11-25 12:09 UTC, walterlv commented on src/dotnetCampus.Configurations/ConfigurationString.cs
> +            return value == null || string.IsNullOrEmpty(value) ? (ConfigurationString?)null : new ConfigurationString(value);
因为可空引用类型的原因，如果不使用前面的 null 判断进行短路，则会编译不通过。

2019-11-25 12:11 UTC, walterlv commented on src/dotnetCampus.Configurations/ConfigurationString.cs
> +            return configurationValue?.ToString() ?? string.Empty;
空传递操作符会使得前者为 null 时传递为 null，即使前者的 null 并不是真正意义上的 null。

2019-11-25 12:12 UTC, walterlv commented on src/dotnetCampus.Configurations/ConfigurationString.cs
> +        /// 注意，空字符串和 null 会被视为相等，因为这两者在 <see cref="ConfigurationString"/> 中表示的是相同含义。
然而不是实现成会了吗？

2019-11-25 12:13 UTC, walterlv commented on src/dotnetCampus.Configurations/ConfigurationString.cs
> +        public override int GetHashCode() => string.IsNullOrEmpty(_value) ? 0 : StringComparer.Ordinal.GetHashCode(_value);
为什么？然而我们规定 null 和 Empty 不区分，在此类型中表示同一个含义。

2019-11-25 12:14 UTC, walterlv commented on src/dotnetCampus.Configurations/Core/ConcurrentAppConfigurator.cs
> +        private readonly Dictionary<Type, Configuration> _configurationDictionary
这里即便使用 ConcurrentDictionary 也无法完成线程安全的代码，因为无法避开两次使用集合。既然必须加锁，那么就没有必要使用 ConcurrentDictionary 了。

2019-11-25 12:26 UTC, kkwpsv commented on src/dotnetCampus.Configurations/ConfigurationString.cs
> +            return configurationValue?.ToString() ?? string.Empty;
configurationValue.ToString()即可

2019-11-25 12:26 UTC, kkwpsv commented on src/dotnetCampus.Configurations/ConfigurationString.cs
> +        /// 注意，空字符串和 null 会被视为相等，因为这两者在 <see cref="ConfigurationString"/> 中表示的是相同含义。
注释实现功能......

2019-12-01 06:58 UTC, lindexi commented on src/dotnetCampus.Configurations/Core/FileConfigurationRepo.cs
> +            string? key = null;
谨慎使用 C# 8.0 如果作源代码包，就要求项目必须升级到 C# 8.0 才能使用，而 C# 8.0 不会默认在 .NET Framework 项目使用

2019-12-01 07:00 UTC, walterlv commented on src/dotnetCampus.Configurations/Core/FileConfigurationRepo.cs
> +            string? key = null;
不用担心，如果项目没有开启 C# 8.0 可空引用类型，则只会在源代码中多一个警告而已。对编译没有任何影响，编译会当作完全没有标记 `?`。

2019-12-23 05:24 UTC, merged