WIP: 跨进程并发读写配置现在更加安全
dotnet-campus/dotnetCampus.Configurations pull request #29
Opened 2020-11-17 12:00 UTC by walterlv

2020-11-19 02:36 UTC, lindexi requested changes

2020-11-19 02:36 UTC, lindexi commented on src/dotnetCampus.Configurations/Core/FileConfigurationRepo.cs
> +        /// 获取此配置与文件的同步次数。
请注明是否包括失败次数

2020-11-19 02:36 UTC, lindexi commented on src/dotnetCampus.Configurations/Core/FileConfigurationRepo.cs
> +        public Task SaveAsync() => SaveAsync(10);
推荐依然是加默认参数的方式，和之前逻辑相同

2020-11-19 02:36 UTC, lindexi commented on src/dotnetCampus.Configurations/Core/FileConfigurationRepo.cs
> +        /// <param name="tryCount">尝试次数。当失败时会尝试重新同步，此值表示算上失败后限制的同步总次数。</param>
加上注释，默认-1表示只重试一次

2020-11-19 02:36 UTC, lindexi commented on src/dotnetCampus.Configurations/Core/FileConfigurationRepo.cs
> +                // 在构造方法中执行时，可能为 null。
这句注释应该放在 else 方法里面，因此这是一个不是空的分支

2020-11-19 02:36 UTC, lindexi commented on src/dotnetCampus.Configurations/Core/FileConfigurationRepo.cs
> +                SetFileTime(handle, keepUnchanged, keepUnchanged, keepUnchanged);
这句话是不是多余的，后续也有文件的更改

2020-11-19 02:36 UTC, lindexi commented on src/dotnetCampus.Configurations/Core/FileConfigurationRepo.cs
> +                long fileTime = timedMerging.Time.ToFileTime();
看起来这是一个调试使用的变量，是否可以干掉

2020-11-19 02:36 UTC, lindexi commented on tests/dotnetCampus.Configurations.Tests/FileConfigurationRepoTests.cs
> +                const string dcc = "configs.03.dcc";
后缀名不是统一作为 coin 了？

2020-11-19 02:36 UTC, lindexi commented on tests/dotnetCampus.Configurations.Tests/FileConfigurationRepoTests.cs
> +                const string dcc = "configs.01.dcc";
听说后缀名统一为 coin 了

2020-11-19 02:36 UTC, lindexi commented on tests/dotnetCampus.Configurations.Tests/FileConfigurationRepoTests.cs
> +                var repoA = CreateIndependentRepo(dcc);
建议实际传入的是让 dcc 文件从临时文件夹获取，用于解决多次单元测试之间的影响

以及后续写单元测试的时候不小心抄代码存在的影响

2020-11-22 01:54 UTC, lindexi commented on src/dotnetCampus.Configurations/Concurrent/CriticalReadWriteContext.cs
> +    public class CriticalReadWriteContext<TKey, TValue> : ICriticalReadWriteContext<TKey, TValue>
看起来可以作为internal 的

2020-11-22 01:54 UTC, lindexi commented on src/dotnetCampus.Configurations/Concurrent/CriticalReadWriteContext.cs
> +        public CriticalReadWriteContext(Func<IReadOnlyDictionary<TKey, TValue>, DateTimeOffset,
推荐定义成接口，而不是委托，因为委托的形式，假定有内存泄露时，难以调试

2020-11-22 01:54 UTC, lindexi commented on src/dotnetCampus.Configurations/Concurrent/ProcessConcurrentDictionary.cs
> +            if (_keyValues.TryRemove(key, out var entry))
看起来返回TryRemove 就可以了，无需自己写判断代码

2020-11-22 01:54 UTC, lindexi commented on src/dotnetCampus.Configurations/Concurrent/ProcessConcurrentDictionary.cs
> +            Debug.WriteLine($"本地更新：{existedEntry.LastUpdateTime}，外部更新：{externalUpdateTime}");
调试完成，建议注释掉，因为源代码包会引用

2020-11-25 13:29 UTC, walterlv commented on src/dotnetCampus.Configurations/Concurrent/ProcessConcurrentDictionary.cs
> +            if (_keyValues.TryRemove(key, out var entry))
你写不出来这样的代码

2020-11-25 13:30 UTC, walterlv commented on tests/dotnetCampus.Configurations.Tests/FileConfigurationRepoTests.cs
> +                var repoA = CreateIndependentRepo(dcc);
这个下次想改的时候一起改

2020-11-26 00:41 UTC, lindexi approved these changes

2020-11-26 01:46 UTC, kkwpsv commented on src/dotnetCampus.Configurations/Concurrent/ProcessConcurrentDictionary.cs
> +            var name = OSUtils.IsPathCaseSensitive() ? path : path.ToUpperInvariant();
文件大小写这里可能有坑

2020-11-26 02:36 UTC, kkwpsv commented
考虑下修改系统时间的情况

2020-11-26 13:09 UTC, lindexi commented on src/dotnetCampus.Configurations.WPFTypeConverter/dotnetCampus.Configurations.WPFTypeConverter.csproj
> +    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.0" PrivateAssets="all" />
看起来在 net45 不需要

2020-11-26 13:10 UTC, lindexi commented on src/dotnetCampus.Configurations/Concurrent/ChangeDetectionType.cs
> +        /// 整个文件中有必须所有内容相同才视为相同。
```suggestion
        /// 整个文件中必须所有内容相同才视为相同。
```

2020-11-26 13:10 UTC, lindexi commented on src/dotnetCampus.Configurations/Concurrent/ChangeDetectionType.cs
> +        /// 无视文件内容，只要新旧文件中包含的键值集合无序相等，则视为相同。
建议加一句，忽略注释的不同

2020-11-26 13:38 UTC, walterlv commented on src/dotnetCampus.Configurations/Concurrent/ChangeDetectionType.cs
> +        /// 无视文件内容，只要新旧文件中包含的键值集合无序相等，则视为相同。
在这个上下文下，不知道注释。另外，你那个问题不是注释，而是“擅自改的”文件头。

2020-11-27 02:04 UTC, lindexi commented on src/dotnetCampus.Configurations/Concurrent/FileDictionarySynchronizer.cs
> +        private DateTimeOffset ReadWriteFile(ICriticalReadWriteContext<TKey, TValue> context, DateTimeOffset lastWriteTime)
是否叫 SyncFileContent 比较好

2020-11-27 02:17 UTC, lindexi commented on src/dotnetCampus.Configurations/Concurrent/FileDictionarySynchronizer.cs
> +        private DateTimeOffset ReadWriteFile(ICriticalReadWriteContext<TKey, TValue> context, DateTimeOffset lastWriteTime)
TryWriteFile

2020-11-27 02:19 UTC, lindexi commented on src/dotnetCampus.Configurations/Concurrent/FileDictionarySynchronizer.cs
> +        private DateTimeOffset ReadWriteFile(ICriticalReadWriteContext<TKey, TValue> context, DateTimeOffset lastWriteTime)
ReadAndWriteFileOrDoNothing

2020-11-27 02:47 UTC, merged